app:
  port: 53
  checkZoneInterval: 5
  checkZoneIntervalType: seconds
  activeCheck: true
  algorithmCheck: RR
  repeatCheckInterval: 3
  repeatCheckIntervalType: seconds
  repeatCheckFileInterval: 3
  repeatCheckFileIntervalType: seconds
  forward: true
  forwardDNS: 8.8.8.8
  forwardDNSPort: 53