app:
  port: 1053
  checkZoneInterval: 5
  checkZoneIntervalType: seconds
  activeCheck: true
  algorithmCheck: RR
  repeatCheckInterval: 3
  repeatCheckIntervalType: seconds
  repeatCheckFileInterval: 3
  repeatCheckFileIntervalType: seconds
  forward: false
  forwardDNS: 8.8.8.8
  forwardDNSPort: 53
  activeLog: true
  pathLog: ./hllb.log
  lvlLog: info
  metricsPort: 9153